# GA Data Science 16 (DAT16) - Lab3
##Developing Mastery of Pandas, Numpy & Bokeh
####  

Justin Breucop (with parts from Craig Sakuma)

## Lab goals

- NumPy: Entering the Matrix
- Pandas: DataFrames as Bamboo
- Bokeh: Picture-Perfect Visuals

##NumPy
As we've seen in lecture, linear algebra is the branch of mathematics describing navigation between different vector spaces. This core concept is very important as a big piece of data cleansing is converting data into various formats and certain algorithms require data to be in a specific shape.

NumPy is a package designed to be used in scientific computing, and specifically around building N-dimensional array objects.

###Creating an array

In [1]:
import numpy as np
a = np.arange(25).reshape(5,5)
# arange(n) is a function that creates a 1 row array of integers of length n 
# reshape(M,N) is a method converts a list to a matrix of size MxN
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

We can convert from lists to arrays. Note however unlike lists, elements of an array all have to be of the same datatype.

In [2]:
alist = [[ 0,  1,  2,  3,  4],[ 5,  6,  7,  8,  9],[10, 11, 12, 13, 14],[15, 16, 17, 18, 19],[20, 21, 22, 23, 24]]
type(alist)

list

In [3]:
np.array(alist)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
biga = a*10
biga

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240]])

In [5]:
print biga.mean()
print biga.mean(0) #Average per column
biga.mean(1) #average per row
# type(biga.mean(1))

120.0
[ 100.  110.  120.  130.  140.]


array([  20.,   70.,  120.,  170.,  220.])

In [6]:
bigm = np.matrix(biga-20)
bigm

matrix([[-20, -10,   0,  10,  20],
        [ 30,  40,  50,  60,  70],
        [ 80,  90, 100, 110, 120],
        [130, 140, 150, 160, 170],
        [180, 190, 200, 210, 220]])

In [7]:
np.linalg.inv(biga-20)

array([[ -1.20181075e+14,   8.72384672e+13,   9.19201624e+13,
          3.51685731e+13,  -9.41461278e+13],
       [  1.29915327e+14,  -4.82534697e+14,   2.33187505e+14,
          4.61567773e+14,  -3.42135908e+14],
       [  1.65462487e+14,   6.77256761e+14,  -7.62120739e+14,
         -1.16937875e+15,   1.08878024e+15],
       [ -2.39946656e+14,  -2.55863299e+14,   4.56998312e+14,
          8.13379896e+14,  -7.74568253e+14],
       [  6.47499164e+13,  -2.60972319e+13,  -1.99852408e+13,
         -1.40737488e+14,   1.22070045e+14]])

####Slices

In [8]:
bigm = np.array(bigm)
bigm[0]

array([-20, -10,   0,  10,  20])

In [9]:
#Same thing, but demonstrating the full slice with a colon
biga[0,:]
biga

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240]])

In [10]:
biga[:,3]

array([ 30,  80, 130, 180, 230])

Slice rules work for even more complex dimensional data

In [11]:
compa = np.arange(30).reshape(5,3,2)
compa

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [12]:
# lets describe it
print compa.shape
print compa.ndim
print compa.dtype

(5L, 3L, 2L)
3
int32


In [13]:
compa[3,:,1]

array([19, 21, 23])

In [14]:
compa[0,0,0]

0

In [15]:
compa[0,0,0] = 5.9
compa[0,0,0]

5

Numpy tries to resolve conflicting datatypes, sometimes to our dismay

In [16]:
compa = compa.astype(float)
compa[0,0,0] = 5.75
compa[0,0,0]

5.75

####Random Numbers
Random numbers are very helpful and are necessary at times for testing data pipelines and running statistical analyses. Functions for creating random values are under numpy.random.

In [17]:
#Create a randomized array
rm = np.random.rand(5,5)
rm

array([[ 0.65596366,  0.86792052,  0.42961131,  0.83632631,  0.46988689],
       [ 0.17738578,  0.53788751,  0.13626354,  0.71914395,  0.38724307],
       [ 0.27218506,  0.25262975,  0.20866113,  0.54922039,  0.89885669],
       [ 0.29908019,  0.35797878,  0.39949641,  0.76114676,  0.79701363],
       [ 0.06534472,  0.89213396,  0.35997641,  0.71788716,  0.65721503]])

In [18]:
rm.shape

(5L, 5L)

In [19]:
print rm.mean()
print rm.mean(0) #Average per column
print rm.mean(1) #average per row

0.508258344379
[ 0.29399188  0.5817101   0.30680176  0.71674491  0.64204306]
[ 0.65194174  0.39158477  0.4363106   0.52294316  0.53851146]


In [20]:
# for a different Normal Distribution, use np.random.normal
rm = np.random.normal(5,9,(30,30))
rm

array([[  1.06012132e+01,   9.76078601e+00,  -1.23632631e+01,
          9.27443066e+00,   1.42198581e+01,   2.38747439e+01,
          6.99374329e+00,  -2.71533176e-01,   2.45726386e+01,
         -1.11192905e+01,   1.59477228e+01,   1.41225333e+01,
          8.61293464e+00,  -9.82170009e+00,   2.76645252e+01,
          1.69982517e+01,   2.25255659e+00,   1.58965397e+01,
         -1.00449265e+01,   9.57456885e+00,   1.04077553e+01,
          5.62673992e+00,   2.84313727e+01,   7.55871475e+00,
         -4.06020479e+00,  -2.74691344e+00,   4.95616281e+00,
         -1.30246521e+01,   1.75681573e+01,   7.46829169e-02],
       [ -5.79100641e+00,   2.58527357e+00,   3.34796952e+00,
          3.68233096e+00,   6.60533788e+00,   1.29881348e+01,
         -3.99289382e-02,   4.95678688e+00,   1.69139779e+01,
          7.15323689e+00,   1.53243428e+01,   3.70249136e+00,
         -8.34705417e+00,  -1.99629088e+00,   2.25497889e+00,
          6.05456680e+00,  -1.53118461e+01,  -6.65188356e+00,
       

In [21]:
print rm.mean(), "which is hopefully close to the input mean"
print rm.var(), "which variance = stdev squared"
print np.median(rm)

4.80998641822 which is hopefully close to the input mean
84.7181329265 which variance = stdev squared
4.62184673555


Find more distributions and random functions here: http://docs.scipy.org/doc/numpy/reference/routines.random.html

###Exercise 1
1) Create a 4x5 array of integers numbering 0 to 19.

In [22]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

2) Create a 50x500 array with a mean of 20 and variance of 100. Save it to a variable called  `biggie`

In [23]:
biggie = np.random.normal(20,10,(50,500))
print biggie.shape
print biggie.mean()
print biggie.var()

(50L, 500L)
19.93655596
100.293796272


3) Change the mean of the array to a value within 1 of 0 and the variance within 1 of 25. Think about what the mean and the variance represent and try using various mathematical operations.

In [24]:
morph = (biggie - 20)/2
print morph.mean()
print morph.var()

-0.0317220200193
25.073449068


##Pandas: DataFrames as Bamboo
You've already been exposed to dataframes in the previous labs so lets get into dataframes and how we can work with them.

In [25]:
import pandas as pd

data = pd.read_csv("titanic-train.csv")
data.head()

PassengerId  Survived  Pclass                                  Name   Sex  \
0          631         1       1  Barkworth, Mr. Algernon Henry Wilson  male   
1          852         0       3                   Svensson, Mr. Johan  male   
2           97         0       1             Goldschmidt, Mr. George B  male   
3          494         0       1               Artagaveytia, Mr. Ramon  male   
4          117         0       3                  Connors, Mr. Patrick  male   

    Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
0  80.0      0      0     27042  30.0000   A23        S  
1  74.0      0      0    347060   7.7750   NaN        S  
2  71.0      0      0  PC 17754  34.6542    A5        C  
3  71.0      0      0  PC 17609  49.5042   NaN        C  
4  70.5      0      0    370369   7.7500   NaN        Q

In [26]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [27]:
data[data.Age>65]

PassengerId  Survived  Pclass                                  Name   Sex  \
0          631         1       1  Barkworth, Mr. Algernon Henry Wilson  male   
1          852         0       3                   Svensson, Mr. Johan  male   
2           97         0       1             Goldschmidt, Mr. George B  male   
3          494         0       1               Artagaveytia, Mr. Ramon  male   
4          117         0       3                  Connors, Mr. Patrick  male   
5          673         0       2           Mitchell, Mr. Henry Michael  male   
6          746         0       1          Crosby, Capt. Edward Gifford  male   
7           34         0       2                 Wheadon, Mr. Edward H  male   

    Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
0  80.0      0      0       27042  30.0000   A23        S  
1  74.0      0      0      347060   7.7750   NaN        S  
2  71.0      0      0    PC 17754  34.6542    A5        C  
3  71.0      0      0    PC 17609  49.5042   NaN        C  
4  70.5      0      0      370369   7.7500   NaN        Q  
5  70.0      0      0  C.A. 24580  10.5000   NaN        S  
6  70.0      1      1   WE/P 5735  71.0000   B22        S  
7  66.0      0      0  C.A. 24579  10.5000   NaN        S

In [28]:
data[(data.Age==11)&(data.SibSp==5)]

PassengerId  Survived  Pclass                                Name   Sex  \
646           60         0       3  Goodwin, Master. William Frederick  male   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked  
646   11      5      2  CA 2144  46.9   NaN        S

In [29]:
data[(data.Age==11)|(data.SibSp==5)]

PassengerId  Survived  Pclass                                 Name  \
614           72         0       3           Goodwin, Miss. Lillian Amy   
641          684         0       3          Goodwin, Mr. Charles Edward   
646           60         0       3   Goodwin, Master. William Frederick   
647          543         0       3    Andersson, Miss. Sigrid Elisabeth   
648          732         0       3             Hassan, Mr. Houssein G N   
649          803         1       1  Carter, Master. William Thornton II   
655          481         0       3       Goodwin, Master. Harold Victor   
704          387         0       3      Goodwin, Master. Sidney Leonard   

        Sex  Age  SibSp  Parch   Ticket      Fare    Cabin Embarked  
614  female   16      5      2  CA 2144   46.9000      NaN        S  
641    male   14      5      2  CA 2144   46.9000      NaN        S  
646    male   11      5      2  CA 2144   46.9000      NaN        S  
647  female   11      4      2   347082   31.2750      NaN        S  
648    male   11      0      0     2699   18.7875      NaN        C  
649    male   11      1      2   113760  120.0000  B96 B98        S  
655    male    9      5      2  CA 2144   46.9000      NaN        S  
704    male    1      5      2  CA 2144   46.9000      NaN        S

###Cleaning Data

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.5+ KB


####Working with nulls
Exclude data

In [31]:
# data[data.Age.isnull()]
data[data.Age.notnull()]

PassengerId  Survived  Pclass  \
0            631         1       1   
1            852         0       3   
2             97         0       1   
3            494         0       1   
4            117         0       3   
5            673         0       2   
6            746         0       1   
7             34         0       2   
8             55         0       1   
9            281         0       3   
10           457         0       1   
11           439         0       1   
12           546         0       1   
13           276         1       1   
14           484         1       3   
15           253         0       1   
16           556         0       1   
17           571         1       2   
18           830         1       1   
19           171         0       1   
20           327         0       3   
21           626         0       1   
22           367         1       1   
23           588         1       1   
24           685         0       2   
25           695         0       1   
26            95         0       3   
27           233         0       2   
28            12         1       1   
29           196         1       1   
..           ...       ...     ...   
684           44         1       2   
685          194         1       2   
686          262         1       3   
687          349         1       3   
688          375         0       3   
689          408         1       2   
690            8         0       3   
691           17         0       3   
692          120         0       3   
693          206         0       3   
694          298         0       1   
695          341         1       2   
696          480         1       3   
697          531         1       2   
698          643         0       3   
699          825         0       3   
700          165         0       3   
701          173         1       3   
702          184         1       2   
703          382         1       3   
704          387         0       3   
705          789         1       3   
706          828         1       2   
707          306         1       1   
708           79         1       2   
709          832         1       2   
710          470         1       3   
711          645         1       3   
712          756         1       2   
713          804         1       3   

                                                 Name     Sex    Age  SibSp  \
0                Barkworth, Mr. Algernon Henry Wilson    male  80.00      0   
1                                 Svensson, Mr. Johan    male  74.00      0   
2                           Goldschmidt, Mr. George B    male  71.00      0   
3                             Artagaveytia, Mr. Ramon    male  71.00      0   
4                                Connors, Mr. Patrick    male  70.50      0   
5                         Mitchell, Mr. Henry Michael    male  70.00      0   
6                        Crosby, Capt. Edward Gifford    male  70.00      1   
7                               Wheadon, Mr. Edward H    male  66.00      0   
8                      Ostby, Mr. Engelhart Cornelius    male  65.00      0   
9                                    Duane, Mr. Frank    male  65.00      0   
10                          Millet, Mr. Francis Davis    male  65.00      0   
11                                  Fortune, Mr. Mark    male  64.00      1   
12                       Nicholson, Mr. Arthur Ernest    male  64.00      0   
13                  Andrews, Miss. Kornelia Theodosia  female  63.00      1   
14                             Turkula, Mrs. (Hedwig)  female  63.00      0   
15                          Stead, Mr. William Thomas    male  62.00      0   
16                                 Wright, Mr. George    male  62.00      0   
17                                 Harris, Mr. George    male  62.00      0   
18          Stone, Mrs. George Nelson (Martha Evelyn)  female  62.00      0   
19                          Van der hoef, Mr. Wyckoff    male  61.00

In [32]:
# You can also just replace the nulls
data.Age[data.Age.isnull()].fillna(0)

714    0
715    0
716    0
717    0
718    0
719    0
720    0
721    0
722    0
723    0
724    0
725    0
726    0
727    0
728    0
729    0
730    0
731    0
732    0
733    0
734    0
735    0
736    0
737    0
738    0
739    0
740    0
741    0
742    0
743    0
      ..
861    0
862    0
863    0
864    0
865    0
866    0
867    0
868    0
869    0
870    0
871    0
872    0
873    0
874    0
875    0
876    0
877    0
878    0
879    0
880    0
881    0
882    0
883    0
884    0
885    0
886    0
887    0
888    0
889    0
890    0
Name: Age, dtype: float64

In [33]:
#Replace with the mean to preserve statistical values
avg_age = data.Age[data.Age.notnull()].mean()
print avg_age
data.Age.fillna(avg_age)

29.6991176471


0      80.000000
1      74.000000
2      71.000000
3      71.000000
4      70.500000
5      70.000000
6      70.000000
7      66.000000
8      65.000000
9      65.000000
10     65.000000
11     64.000000
12     64.000000
13     63.000000
14     63.000000
15     62.000000
16     62.000000
17     62.000000
18     62.000000
19     61.000000
20     61.000000
21     61.000000
22     60.000000
23     60.000000
24     60.000000
25     60.000000
26     59.000000
27     59.000000
28     58.000000
29     58.000000
         ...    
861    29.699118
862    29.699118
863    29.699118
864    29.699118
865    29.699118
866    29.699118
867    29.699118
868    29.699118
869    29.699118
870    29.699118
871    29.699118
872    29.699118
873    29.699118
874    29.699118
875    29.699118
876    29.699118
877    29.699118
878    29.699118
879    29.699118
880    29.699118
881    29.699118
882    29.699118
883    29.699118
884    29.699118
885    29.699118
886    29.699118
887    29.699118
888    29.6991

####Replace with random normal distribution

In [34]:
# Get values of mean and standard deviation
data.Age[data.Age.notnull()].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [35]:
# Replace null values with 
data.Age.fillna(np.random.normal(29.7,14.5),inplace=True)

In [36]:
data.Age.fillna(np.random.normal(29.7,14.5)).describe()

count    891.000000
mean      29.963351
std       13.012854
min        0.420000
25%       22.000000
50%       31.029243
75%       35.000000
max       80.000000
Name: Age, dtype: float64

###Convert categorical data to numerical

In [37]:
data.Sex=='female'

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13      True
14      True
15     False
16     False
17     False
18      True
19     False
20     False
21     False
22      True
23     False
24     False
25     False
26     False
27     False
28      True
29      True
       ...  
861    False
862     True
863    False
864    False
865    False
866    False
867    False
868    False
869    False
870    False
871    False
872    False
873    False
874    False
875     True
876    False
877    False
878    False
879    False
880    False
881    False
882    False
883    False
884    False
885     True
886    False
887     True
888    False
889    False
890     True
Name: Sex, dtype: bool

In [38]:
data.rename(columns={'Sex':'Is Female'},inplace=True)
data['Is Female']=data['Is Female']=='female'
data.head()

PassengerId  Survived  Pclass                                  Name  \
0          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
1          852         0       3                   Svensson, Mr. Johan   
2           97         0       1             Goldschmidt, Mr. George B   
3          494         0       1               Artagaveytia, Mr. Ramon   
4          117         0       3                  Connors, Mr. Patrick   

  Is Female   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
0     False  80.0      0      0     27042  30.0000   A23        S  
1     False  74.0      0      0    347060   7.7750   NaN        S  
2     False  71.0      0      0  PC 17754  34.6542    A5        C  
3     False  71.0      0      0  PC 17609  49.5042   NaN        C  
4     False  70.5      0      0    370369   7.7500   NaN        Q

In [39]:
# get unique values of Embarked
data.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [42]:
# replace values with numbers
data.Embarked.replace(['S', 'C', 'Q', 'nan'],[1,2,3,4],inplace=True)
data.head()

PassengerId  Survived  Pclass                                  Name  \
0          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
1          852         0       3                   Svensson, Mr. Johan   
2           97         0       1             Goldschmidt, Mr. George B   
3          494         0       1               Artagaveytia, Mr. Ramon   
4          117         0       3                  Connors, Mr. Patrick   

  Is Female   Age  SibSp  Parch    Ticket     Fare Cabin  Embarked  
0     False  80.0      0      0     27042  30.0000   A23         1  
1     False  74.0      0      0    347060   7.7750   NaN         1  
2     False  71.0      0      0  PC 17754  34.6542    A5         2  
3     False  71.0      0      0  PC 17609  49.5042   NaN         2  
4     False  70.5      0      0    370369   7.7500   NaN         3

###Selecting with .loc, .iloc, & .ix

Selecting data in pandas can be tricky. The main takeaway is that .loc looks for index labels, .iloc looks for the integer index position, and .ix can be a mix. 

In [ ]:
df = pd.DataFrame(np.random.randn(6,4),index=list('abcdef'),columns=list('ABCD'))
df

In [ ]:
df.loc['f']

In [ ]:
df.iloc[len(df.index)-1]

In [ ]:
df.A.ix['f'] == df.A.ix[-1]

In [ ]:
cc = list('cookies')
cc[-4]

###Group by

In [ ]:
# Find average age of passengers that survived vs. died
data.groupby('Survived')['Age'].mean()

In [ ]:
# Count number of female passengers
data.groupby('Is Female')['PassengerId'].count()

In [ ]:
data.groupby(['Survived','Pclass'])['PassengerId'].count()

###Apply

In [ ]:


# Convert ticket prices to USD
data.Fare.apply(lambda x: x*1.6)

In [ ]:
data.Name

In [ ]:
data.Name.apply(lambda x: x.split(",")[0])

###Concatenate

In [ ]:
data_first_half = data.iloc[0:10,:]
data_first_half.info()

In [ ]:
data_second_half = data.iloc[10:,:]

remake_data = pd.concat([data_first_half,data_second_half])
remake_data.info()

###EXERCISE 2
1) Replace Pclass numbers with 'First Class', 'Second Class', 'Third Class'

2) What was the average ticket price for survivors vs. dead passengers?

###Bonus!!!
Round all ages to the nearest year using `apply`

##Bokeh: Picture Perfect Visuals

To install Bokeh, go to a terminal and type:

`conda install bokeh` 

Bokeh is built by the same people that created Anaconda (Continuum Analytics) and is designed out of the box for web display, making it nice for creating presentation ready, interactive visuals quickly. Labs in this course will be shown in Bokeh. Checkout http://bokeh.pydata.org/en/latest/docs/quickstart.html#concepts to see some of the range of capabilities.

In [ ]:
from bokeh.plotting import figure, output_notebook,show,vplot
output_notebook()

In [ ]:
import pandas.io.data
import datetime
aapl = pd.io.data.get_data_yahoo('FB', 
                                 start=datetime.datetime(2015, 4, 1), 
                                 end=datetime.datetime(2015, 4, 28))


In [ ]:
# prepare some data
x = aapl.Low
y = aapl.High

# create a new plot with a title and axis labels
p = figure(title="Stock High vs. Low", x_axis_label='Low', y_axis_label='High')

# These are glyphs
p.circle(x, y,size=30,alpha=.5,)
p.line(x,x*y.mean()/x.mean())

# show the results
show(p)

At its core, Bokeh is built up with Plots and Glyphs. Plots are created with the figure keyword and then glyphs are visuals that are added to the visualization. The visuals are scalable, interactive and savable. You can even create vectorized colors.

In [ ]:
# prepare some data
N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = ["#%02x%02x%02x" % (r, g, 150) for r, g in zip(np.floor(50+2*x), np.floor(30+2*y))]

TOOLS="resize,crosshair,pan,wheel_zoom,box_zoom,reset,box_select,lasso_select"

# create a new plot with the tools above, and explicit ranges
p = figure(tools=TOOLS, x_range=(0,100), y_range=(0,100))

# add a circle renderer with vecorized colors and sizes
p.circle(x,y, radius=radii, fill_color=colors, fill_alpha=0.6, line_color=None)

# show the results
show(p)

In [ ]:
p1 = figure(title="Titanic Ages Dead",x_axis_label = 'Age',y_axis_label = 'Count')
#construct the histogram
hist, edges = np.histogram(data.Age[data.Survived==0].values, density=True, bins=50)
#Construct your x axis
x = np.linspace(data.Age.min(),data.Age.max(),100)
#add the bars, scaling the value to the full count of people
p1.quad(top=hist*len(data.Age), bottom=0, left=edges[:-1], right=edges[1:],line_color='black')

p2 = figure(title="Titanic Ages Survived",x_axis_label = 'Age',y_axis_label = 'Count')

hist, edges = np.histogram(data.Age[data.Survived==1].values, density=True, bins=50)
x = np.linspace(data.Age.min(),data.Age.max(),100)
p2.quad(top=hist*len(data.Age), bottom=0, left=edges[:-1], right=edges[1:],line_color='black')


show(vplot(p1,p2))